[lint]
select = [
    # Doc style
    "D",
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
ignore = [
    # Incompatible with D211 (no-blank-line-before-class)
    "D203",
    # Incompatible with D212 (multi-line-summary-first-line)
    "D213",
]
